begin;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users (id) on delete cascade,
  reported_entity_type text not null,
  reported_entity_id text not null,
  reason text not null,
  description text null,
  selected_flags text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create table if not exists public.discussion_raises (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_id text not null,
  source_table text not null check (source_table in ('discussions', 'comments')),
  created_at timestamptz not null default now()
);

create unique index if not exists reports_unique_reporter_entity_idx
  on public.reports (reporter_id, reported_entity_type, reported_entity_id);

create unique index if not exists discussion_raises_unique_user_entry_idx
  on public.discussion_raises (user_id, entry_id, source_table);

create index if not exists reports_entity_lookup_idx
  on public.reports (reported_entity_type, reported_entity_id, created_at desc);

create index if not exists reports_reporter_lookup_idx
  on public.reports (reporter_id, created_at desc);

create index if not exists discussion_raises_entry_lookup_idx
  on public.discussion_raises (source_table, entry_id, created_at desc);

create index if not exists discussion_raises_user_lookup_idx
  on public.discussion_raises (user_id, created_at desc);

alter table public.reports enable row level security;
alter table public.discussion_raises enable row level security;

drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own"
  on public.reports
  for insert
  to authenticated
  with check (reporter_id = auth.uid());

drop policy if exists "reports_select_own" on public.reports;
create policy "reports_select_own"
  on public.reports
  for select
  to authenticated
  using (reporter_id = auth.uid());

drop policy if exists "reports_select_admin" on public.reports;
create policy "reports_select_admin"
  on public.reports
  for select
  to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '') in ('super_admin', 'lgu_admin', 'barangay_admin', 'admin')
  );

drop policy if exists "discussion_raises_insert_own" on public.discussion_raises;
create policy "discussion_raises_insert_own"
  on public.discussion_raises
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "discussion_raises_select_own" on public.discussion_raises;
create policy "discussion_raises_select_own"
  on public.discussion_raises
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "discussion_raises_delete_own" on public.discussion_raises;
create policy "discussion_raises_delete_own"
  on public.discussion_raises
  for delete
  to authenticated
  using (user_id = auth.uid());

commit;
